experiment:
  name: blip3o
  seed: 42

dataset:
  type: blip3o
  path: None
  max_images: 0

image:
  resolution: 512

weights_calculation:
  batch_size: 128
  num_steps: 500
  padded: true

rapsd:
  # If you don't want to use the precomputed RAPSD results, set this to false and specify the dataset path above. Results will be saved to the cache path below.
  use_precomputed: true
  cache: "./rapsd_cache/blip3o_60k_rapsd_results_512.pkl"

frequencies:
  mode: 0
  pixel_size: 0.000114
  viewing_distance: 0.5

figures:
  reproduce_figures: true
  directory: "./figures"
  plot_num_steps: 50

output:
  directory: "./results"
